SELECT no_empresa,	no_folio_det,	no_folio_mov,	id_tipo_operacion,	id_cve_operacion,	id_tipo_saldo,	no_linea,	id_inv_cbolsa,	no_cuenta,	id_estatus_mov,	no_cheque,	id_chequera,	id_banco,	id_forma_pago,	importe,	importe_original,	b_salvo_buen_cobro,	id_tipo_docto,	no_docto,	valor_tasa,	fec_operacion,	fec_valor,	fec_valor_original,	fec_recalculo,	folio_ref,	dias_inv,	id_tipo_movto,	id_caja,	id_divisa,	id_divisa_original,	fec_exportacion,	fec_reimprime,	fec_imprime,	fec_cheque,	lote_entrada,	lote_salida,	referencia,	folio_banco,	beneficiario,	id_leyenda,	id_banco_benef,	id_chequera_benef,	concepto,	id_contable,	folio_seg,	arch_protegido,	usuario_imprime,	fec_alta,	usuario_alta,	fec_modif,	usuario_modif,	no_cuenta_ref,	id_estatus_cb,	id_estatus_cc,	no_cliente,	no_cobrador,	sucursal,	plaza,	observacion,	no_recibo,	origen_mov,	no_docto_cus,	solicita,	autoriza,	b_entregado,	importe_desglosado,	fec_entregado,	fec_conf_trans,	fec_rech_trans,	tipo_cambio,	tipo_cancelacion,	fec_exporta_flujo,	fec_trans,	b_gen_contable,	id_codigo,	id_subcodigo,	fisica_moral,	nac_ext,	id_estatus_cheq,	invoice_id,	vendor_id,	vendor_site_id,	invoice_type,	no_factura,	grupo_pago,	id_rubro,	agrupa1,	agrupa2,	agrupa3,	po_headers,	alternate_vendor_id_eft,	alternate_vendor_site_id_eft,	invoice_type_lookup_code,	b_autoriza_impre,	firmante1,	firmante2,	oper_may_esp,	cod_bloqueo,	rfc,	b_gen_conta,	no_poliza,	c_poliza,	c_lote,	c_periodo,	c_mes,	division,	ind_iva,	contrarecibo,	deudor,	descripcion,	rango,	no_pedido,	referencia_ban,	hora_recibo,	fec_concilia_caja,	fec_propuesta,	importe_parcial,	b_arch_seg,	cve_control,	id_banco_ant,	id_chequera_ant,	origen_mov_ant,	no_cliente_ant,	id_servicio_be,	e_mail,	clabe,	id_area,	monto_sobregiro,	fec_propone_mov,	usu_propone_mov,	id_grupo,	tabla_origen,	fecha_contabilizacion,	b_certificado,	fec_certificacion,	abba,	swift,	nombre_prov_divisas,	banco_divisas,	direccion_divisas,	cuenta_divisas,	sort_code,	abi,	cab,	comentario1,	comentario2
FROM (
SELECT 
        ROW_NUMBER() OVER (ORDER BY no_folio_det) AS rowid ,
        COALESCE(no_empresa,0) as no_empresa ,
        COALESCE(no_folio_det,0) as no_folio_det,
        COALESCE(no_folio_mov,0) as no_folio_mov,
        COALESCE(id_tipo_operacion,0) as id_tipo_operacion,
        COALESCE(id_cve_operacion,0) as id_cve_operacion,
        COALESCE(id_tipo_saldo,0) as id_tipo_saldo,
        COALESCE(no_linea,0) as no_linea,
        COALESCE(id_inv_cbolsa,0) as id_inv_cbolsa,
        COALESCE(no_cuenta,0) as no_cuenta,
        id_estatus_mov,
	    COALESCE(no_cheque,0) as no_cheque,
        id_chequera,
        COALESCE(id_banco ,0) as id_banco,
        COALESCE(id_forma_pago,0) as id_forma_pago,
        importe,
        importe_original,
        b_salvo_buen_cobro,
        COALESCE(id_tipo_docto,0) as id_tipo_docto,
        no_docto,
        COALESCE(valor_tasa,0) as valor_tasa,
        COALESCE(fec_operacion,'') as fec_operacion ,
        COALESCE(fec_valor,'') as fec_valor,
        COALESCE(fec_valor_original,'') as fec_valor_original,
        COALESCE(fec_recalculo,'') as fec_recalculo,
        COALESCE(folio_ref,0) as folio_ref,     
        COALESCE(dias_inv,0) as dias_inv,
        id_tipo_movto,
        COALESCE(id_caja ,0) as id_caja,
        id_divisa,
        id_divisa_original,
        COALESCE(fec_exportacion,'') as fec_exportacion,
        COALESCE(fec_reimprime,'') as fec_reimprime ,
        COALESCE(fec_imprime,'') as fec_imprime ,
        COALESCE(fec_cheque,'') as fec_cheque,
        COALESCE(lote_entrada,0) as lote_entrada,
	    COALESCE(lote_salida,0) as lote_salida,
	    replace(replace(replace(replace(referencia,'"',''),char(13),' '),char(10),' '),'|','')as referencia,
	     replace(replace(replace(replace(folio_banco,'"',''),char(13),' '),char(10),' '),'|','')as folio_banco,
        replace(replace(replace(replace(beneficiario,'"',''),char(13),' '),char(10),' '),'|','') as beneficiario,
        id_leyenda,
        COALESCE(id_banco_benef,0) as id_banco_benef,
        id_chequera_benef,
        REPLACE(replace(replace(replace(concepto,char(13),' '),char(10),' '),'"',''),'|','') as concepto,
        REPLACE(replace(replace(replace(id_contable,char(13),' '),char(10),' '),'"',''),'|','') as id_contable,
        COALESCE(folio_seg,0) as folio_seg,
        arch_protegido,
        COALESCE(usuario_imprime,0) as usuario_imprime,
        COALESCE(fec_alta,'') as fec_alta,
        COALESCE(usuario_alta,0) as usuario_alta ,
        COALESCE(fec_modif,'') as  fec_modif,
        COALESCE(usuario_modif,0) as usuario_modif,
        COALESCE(no_cuenta_ref,0) as no_cuenta_ref,
        id_estatus_cb,
        id_estatus_cc,
        no_cliente,
        COALESCE(no_cobrador,0) as no_cobrador,
        COALESCE(sucursal,0) as sucursal,
        COALESCE(plaza,0) as plaza ,
        REPLACE(replace(replace(replace(observacion,char(13),' '),char(10),' '),'"',''),'|','') as observacion,
        COALESCE(no_recibo,0) as no_recibo,
        origen_mov,
        no_docto_cus,
        solicita,
        autoriza,
        b_entregado,
        COALESCE(importe_desglosado,0) as importe_desglosado,
        COALESCE(fec_entregado,'') as fec_entregado ,
        COALESCE(fec_conf_trans,'') as fec_conf_trans ,
        COALESCE(fec_rech_trans,'')  as  fec_rech_trans, 
        tipo_cambio,
        tipo_cancelacion,
        COALESCE(fec_exporta_flujo,'') as fec_exporta_flujo ,
        COALESCE(fec_trans,'') as fec_trans,
        b_gen_contable,
        id_codigo,
        id_subcodigo,
        fisica_moral,
        nac_ext,
        id_estatus_cheq,
        COALESCE(invoice_id,0) as invoice_id,
        COALESCE(vendor_id,0) as vendor_id,
        COALESCE(vendor_site_id,0) as vendor_site_id,
        invoice_type,
        no_factura,
        COALESCE(grupo_pago,0) as grupo_pago,
        id_rubro,
        COALESCE(agrupa1,0) as agrupa1,
	    COALESCE(agrupa2,0) as agrupa2,
	    COALESCE(agrupa3,0) as agrupa3,
        po_headers,
        alternate_vendor_id_eft,
        alternate_vendor_site_id_eft,
        invoice_type_lookup_code,
        b_autoriza_impre,
        COALESCE(firmante1,0) as firmante1,
        COALESCE(firmante2,0) as firmante2,
        oper_may_esp,
        cod_bloqueo,
        rfc,
        b_gen_conta,
        COALESCE(no_poliza,0) as no_poliza,
        COALESCE(c_poliza,0) as c_poliza,
		COALESCE(c_lote,0) as c_lote,
		COALESCE(c_periodo,0) as c_periodo,
		COALESCE(c_mes,0) as c_mes,
        division,
        ind_iva,
        contrarecibo,
        deudor,
        REPLACE(replace(replace(replace(descripcion,char(13),' '),char(10),' '),'"',''),'|','') as  descripcion,
        rango,
        COALESCE(no_pedido,0) as no_pedido,
        referencia_ban,
        hora_recibo,
        COALESCE(fec_concilia_caja,'') as fec_concilia_caja,
        COALESCE(fec_propuesta,'') as fec_propuesta,
        COALESCE(importe_parcial,0) as importe_parcial,
        b_arch_seg,
        cve_control,
        COALESCE(id_banco_ant,0) as id_banco_ant,
        id_chequera_ant,
        origen_mov_ant,
        no_cliente_ant,
        id_servicio_be,
        REPLACE(replace(replace(replace(e_mail,char(13),' '),char(10),' '),'"',''),'|','') as e_mail,
        clabe,
        COALESCE(id_area,0) as id_area,
        COALESCE(monto_sobregiro,0) as monto_sobregiro,
        COALESCE(fec_propone_mov,'') as fec_propone_mov,
        COALESCE(usu_propone_mov,0) as usu_propone_mov,
        COALESCE(id_grupo,0) as id_grupo,
        tabla_origen,
        COALESCE(fecha_contabilizacion,'') as fecha_contabilizacion,
        b_certificado,
        COALESCE(fec_certificacion,'') as fec_certificacion,
        abba,
        swift,
        nombre_prov_divisas,
        banco_divisas,
        direccion_divisas,
        cuenta_divisas,
        sort_code,
        abi,
        cab,
        comentario1,
        comentario2
FROM  hist_movimiento
--where no_folio_det in ('4969110')

)X
--WHERE rowid>1000000
--and no_folio_det=1801023

--(1420743 row(s) affected)

