select 
t1.no_empresa,
t1.no_folio_det,
t1.no_folio_mov,
3201 as id_tipo_operacion,
t1.id_cve_operacion,
t1.id_tipo_saldo,
t1.no_linea,
t1.id_inv_cbolsa,
t1.no_cuenta,
t2.id_estatus_mov,
t1.no_cheque,
t1.id_chequera,
t1.id_banco,
t1.id_forma_pago,
t1.importe,
t1.importe_original,
t1.b_salvo_buen_cobro,
t1.id_tipo_docto,
t1.no_docto,
t1.valor_tasa,
t1.fec_operacion,
t1.fec_valor,
t1.fec_valor_original,
t1.fec_recalculo,
t1.no_folio_det as folio_ref,
t1.dias_inv,
t1.id_tipo_movto,
t1.id_caja,
t1.id_divisa,
t1.id_divisa_original,
t1.fec_exportacion,
t1.fec_reimprime,
t1.fec_imprime,
t1.fec_cheque,
t1.lote_entrada,
t1.lote_salida,
t1.referencia,
t1.folio_banco,
t1.beneficiario,
t1.id_leyenda,
t1.id_banco_benef,
t1.id_chequera_benef,
t1.concepto,
t1.id_contable,
t1.folio_seg,
t1.arch_protegido,
t1.usuario_imprime,
t1.fec_alta,
t1.usuario_alta,
t1.fec_modif,
t1.usuario_modif,
t1.no_cuenta_ref,
t1.id_estatus_cb,
t1.id_estatus_cc,
t1.no_cliente,
t1.no_cobrador,
t1.sucursal,
t1.plaza,
t1.observacion,
t1.no_recibo,
t1.origen_mov,
t1.no_docto_cus,
t1.solicita,
t1.autoriza,
t1.b_entregado,
t1.importe_desglosado,
t1.fec_entregado,
t1.fec_conf_trans,
t1.fec_rech_trans,
t1.tipo_cambio,
t1.tipo_cancelacion,
t1.fec_exporta_flujo,
t1.fec_trans,
t1.b_gen_contable,
t1.id_codigo,
t1.id_subcodigo,
t1.fisica_moral,
t1.nac_ext,
t1.id_estatus_cheq,
t1.invoice_id,
t1.vendor_id,
t1.vendor_site_id,
t1.invoice_type,
t1.no_factura,
case when t1.grupo_pago is null  then t1.no_folio_det else t1.grupo_pago end as grupo_pago,
--t1.grupo_pago,
t1.id_rubro,
t1.agrupa1,
t1.agrupa2,
t1.agrupa3,
t1.po_headers,
t1.alternate_vendor_id_eft,
t1.alternate_vendor_site_id_eft,
t1.invoice_type_lookup_code,
t1.b_autoriza_impre,
t1.firmante1,
t1.firmante2,
t1.oper_may_esp,
t1.cod_bloqueo,
t1.rfc,
t1.b_gen_conta,
t1.no_poliza,
t1.c_poliza,
t1.c_lote,
t1.c_periodo,
t1.c_mes,
t1.Division,
t1.Ind_IVA,
t1.contrarecibo,
t1.deudor,
t1.descripcion,
t1.rango,
t1.no_pedido,
t1.referencia_ban,
t1.hora_recibo,
t1.fec_concilia_caja,
t1.fec_propuesta,
t1.importe_parcial,
t1.b_arch_seg,
t1.cve_control,
t1.id_banco_ant,
t1.id_chequera_ant,
t1.origen_mov_ant,
t1.no_cliente_ant,
t1.id_servicio_be,
t1.e_mail,
t1.clabe,
t1.id_area,
t1.monto_sobregiro,
t1.fec_propone_mov,
t1.usu_propone_mov,
t1.id_grupo,
t1.tabla_origen,
t1.fecha_contabilizacion,
t1.b_certificado,
t1.fec_certificacion,
t1.abba,
t1.swift,
t1.nombre_prov_divisas,
t1.banco_divisas,
t1.direccion_divisas,
t1.cuenta_divisas,
t1.sort_code,
t1.abi,
t1.cab,
t1.comentario1,
t1.comentario2,
'Complemento a 3201' as tblSource
from  `mx-herdez-analytics.sethdzqa.TransfPropuestasR3000` t1
inner join 
          (
         
                  SELECT t1.no_folio_det,t1.no_docto,t2.id_estatus_mov
                            FROM   `mx-herdez-analytics.sethdzqa.TransfPropuestasR3000` t1
                            inner join (select 
                                        case when a.grupo_pago =0 then a.folio_ref else  a.grupo_pago end as grupo_pago
                                        ,id_estatus_mov
                                        FROM `mx-herdez-analytics.sethdzqa.v_zimp_fact_trans` t1
										left join  `mx-herdez-analytics.sethdzqa.TransfPagosR3200` a on t1.no_doc_sap= a.no_docto
                                         where  a.id_estatus_mov in ('K','T') 
                                         -- and a.grupo_pago<>0
                                        group by 
                                        case when a.grupo_pago =0 then a.folio_ref else  a.grupo_pago end
                                        ,a.id_estatus_mov
                                        ) t2 on t1.grupo_pago=t2.grupo_pago
                  group by t1.no_docto,t1.no_folio_det,t2.id_estatus_mov

          )t2 on t1.no_docto=t2.no_docto and t1.no_folio_det=t2.no_folio_det
where 1=1